# controller_list:
#   - name: ""
#     action_ns: joint_trajectory_action
#     type: FollowJointTrajectory
#     joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]


controller_list:
 - name: "/egm/joint_velocity_trajectory_controller"
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

#  - name: "/egm/joint_group_velocity_controller"
#    action_ns: follow_joint_trajectory
#    type: FollowJointTrajectory
#    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

#  - name: "/egm/joint_position_trajectory_controller"
#    action_ns: follow_joint_trajectory
#    type: FollowJointTrajectory
#    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
